pip install discord
pip install whois
pip install colorama
pip install inputimeout
pip install datetime 
pip install requests 
pip install asyncio 
pip install language 
pip install bs4 
pip install pymongo 
pip install selenium 
pip install pyPrivnote 
pip install gtts 
pip install tqdm 
